# Generated by Django 4.0.1 on 2023-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
